/**
 * Documentation-retrieval layer for the QAIL MCP server.
 *
 * The six WASM tools answer questions about a snippet the agent already has
 * ("parse this", "transpile that"). They cannot answer "how do I write an
 * upsert" or "what does the schema DSL look like", because the answer lives in
 * prose the agent has never seen. This module closes that gap: it ships the
 * repo's documentation as a pre-chunked, pre-indexed bundle and exposes it as
 * five retrieval tools plus three always-loadable orientation resources.
 *
 * Everything here is pure and synchronous. The corpus and the BM25 index are
 * JSON imports, so they are baked into the Worker bundle at build time — there
 * is no KV lookup, no network call, and no cold-start I/O, which matters
 * because Workers forbids async work in global scope and every millisecond
 * here is billed CPU.
 *
 * The corpus and index are produced by `core/examples/knowledge_export.rs` plus
 * the corpus builder; this file only reads them. If their schema changes, the
 * accessors at the top of this file are the only place that needs to follow.
 */

// The version string comes from the WASM module so search footers can never
// drift from the parser that actually answers qail_parse_query. It is read
// lazily inside request handling: `initSync` runs in index.ts module scope, and
// calling into WASM before that would touch uninitialised memory.
import { version } from "./wasm/qail_wasm.js";

import corpusJson from "./knowledge/corpus.json";
import indexJson from "./knowledge/index.json";

/* -------------------------------------------------------------------------- */
/* Corpus shape                                                               */
/* -------------------------------------------------------------------------- */

interface Chunk {
    /** Stable retrieval handle, quoted in every result so qail_doc can fetch it. */
    id: string;
    /** Repo-relative source path, e.g. "docs/src/reference/queries.md". */
    path: string;
    /**
     * One of the eight kinds the builder emits:
     * "guide" | "production" | "example-code" | "example" | "crate-readme"
     * | "sdk-readme" | "schema-sample" | "negative".
     */
    kind: string;
    /** Coarse subsystem bucket, e.g. "core", "gateway", "sdk", "grammar". */
    area: string;
    title: string;
    /** Ancestor headings, outermost first. Empty for non-markdown chunks. */
    headingPath: string[];
    content: string;
    tokens: number;
    /** Editorial boost. Verified examples outrank prose; changelogs are excluded upstream. */
    weight: number;
    /**
     * Schema dialect this chunk teaches, when it teaches one.
     * "paren" marks the LEGACY `table users ( ... )` syntax parsed only by
     * core/src/parser/schema.rs. It is filtered out of every result below,
     * unconditionally — an agent that learns it will write schemas that the
     * migration and codegen parsers both reject.
     */
    dialect: string | null;
}

interface Bm25Index {
    /** term -> number of chunks containing it. */
    df: Record<string, number>;
    /** term -> [chunkIndex, termFrequency][]. */
    postings: Record<string, [number, number][]>;
    /** Token length per chunk, parallel to the corpus array. */
    len: number[];
    avgLen: number;
    /** Corpus size the index was built against. */
    n: number;
}

const CHUNKS = (corpusJson as unknown as Chunk[]) ?? [];
const INDEX = indexJson as unknown as Bm25Index;

/**
 * The builder creates these maps with Object.create(null), but a null prototype
 * does not survive JSON serialisation: after the import they are ordinary
 * objects, so `POSTINGS[term]` for a term like "constructor" or "toString" would
 * walk the prototype chain and hand back a function that passes a truthy guard
 * and then throws when destructured. Rehydrate the null prototype once, here, so
 * every lookup below is an own-property read by construction.
 */
const POSTINGS: Record<string, [number, number][]> = Object.assign(
    Object.create(null) as Record<string, [number, number][]>,
    INDEX?.postings ?? {},
);
const DF: Record<string, number> = Object.assign(
    Object.create(null) as Record<string, number>,
    INDEX?.df ?? {},
);

/**
 * The corpus and the index are generated by a separate build step. If they ever
 * disagree — a stale index, a partial regeneration — BM25 would silently score
 * against the wrong documents. Detect that once, at module scope, and fall back
 * to a literal scorer rather than returning confidently wrong results.
 */
const INDEX_USABLE =
    !!INDEX &&
    !!INDEX.postings &&
    !!INDEX.df &&
    Array.isArray(INDEX.len) &&
    INDEX.len.length === CHUNKS.length &&
    INDEX.avgLen > 0;

/** Chunks the agent is allowed to see, as indices into CHUNKS. */
const VISIBLE: number[] = CHUNKS.map((_, i) => i).filter((i) => CHUNKS[i].dialect !== "paren");
const VISIBLE_SET = new Set(VISIBLE);

function qailVersion(): string {
    try {
        return version();
    } catch {
        // Reached only if a caller invokes a knowledge tool before initSync,
        // which the Worker's control flow makes impossible. Degrade rather than
        // fail a request over a footer string.
        return "unknown";
    }
}

/* -------------------------------------------------------------------------- */
/* Tokenisation and query expansion                                           */
/* -------------------------------------------------------------------------- */

/**
 * Must match the tokeniser that built index.json, which was verified against
 * the shipped vocabulary: lowercase, split on every non-alphanumeric character
 * (underscores included, so `parse_where_clause` indexes as parse/clause), drop
 * anything shorter than two characters, drop stopwords.
 *
 * Asymmetric on stemming, deliberately. The BUILDER indexes each token and, for
 * plurals, its singular stem as well, so the vocabulary holds both `fields` and
 * `field`. Queries are NOT stemmed here: a query term is looked up as written
 * and finds its own posting list either way, while stemming the query too would
 * collapse distinct QAIL keywords (`set` into `sets`). The index is a superset
 * of the text; chunk lengths in index.json count only the unstemmed tokens, so
 * the stems do not distort BM25 length normalisation.
 *
 * A query term missing from the index simply scores nothing, so an
 * over-inclusive stopword list is the only way to actually lose signal. Every
 * word below was checked against the shipped vocabulary and is absent from it;
 * `use` and `using` were removed after the check because the index does keep
 * them, and `using` is load-bearing in MERGE syntax.
 *
 * The list still earns its place: the literal fallback scorer and the snippet
 * window both use these terms, and there a match on "the" is pure noise.
 */
const STOPWORDS = new Set([
    "a", "an", "and", "are", "as", "at", "be", "but", "by", "can", "do", "does",
    "for", "from", "has", "have", "how", "i", "if", "in", "into", "is", "it",
    "its", "me", "my", "no", "not", "of", "on", "or", "should", "so", "than",
    "that", "the", "their", "them", "then", "there", "these", "they", "this",
    "to", "was", "what", "when", "where", "which", "will", "with", "would",
    "you", "your",

    // Instructional filler. These carry no intent in a question but are real,
    // reasonably rare terms in the prose, so an unfiltered "how do I write an
    // upsert" ranks every page that happens to discuss writes above the actual
    // conflict documentation. Measured against the shipped corpus.
    "write", "writes", "writing", "wrote", "want", "wants", "need", "needs",
    "please", "tell", "explain", "way", "thing", "things", "doing",
]);

function tokenize(text: string): string[] {
    const out: string[] = [];
    for (const raw of text.toLowerCase().split(/[^a-z0-9]+/)) {
        if (raw.length < 2) continue;
        if (STOPWORDS.has(raw)) continue;
        out.push(raw);
    }
    return out;
}

/**
 * Agents arrive thinking in SQL. Someone searching "insert on conflict" must
 * land on the `add` / `conflict` documentation even though neither word appears
 * in their query, so the query is expanded through this map before scoring.
 *
 * Two QAIL keywords are deliberately absent as expansion *targets*: `where` and
 * `with`. Both are English stopwords, so the index generator dropped them from
 * the vocabulary and expanding to them would score exactly zero. Queries about
 * those constructs are routed to the words that were indexed instead
 * (`condition`, `clause`, `cte`), which is why the right-hand sides below are
 * not simply the QAIL keyword in every case.
 */
const ALIASES: Record<string, string[]> = Object.assign(Object.create(null) as Record<string, string[]>, {
    // Actions. get/add/set/del/merge are the five DML verbs.
    select: ["get"],
    query: ["get"],
    read: ["get"],
    fetch: ["get"],
    insert: ["add"],
    create: ["add"],
    update: ["set"],
    modify: ["set"],
    delete: ["del"],
    remove: ["del"],
    drop: ["del"],
    upsert: ["conflict", "add"],
    conflict: ["conflict", "add"],
    merge: ["merge"],

    // Clauses. `with` is unindexed, so CTE questions route through "cte".
    join: ["join"],
    joins: ["join"],
    cte: ["cte", "recursive"],
    recursive: ["recursive", "cte"],
    subquery: ["subquery", "cte"],
    order: ["order", "sort"],
    sort: ["order"],
    sorting: ["order"],
    group: ["group", "having"],
    aggregate: ["group", "having"],
    limit: ["limit", "offset"],
    paginate: ["limit", "offset"],
    pagination: ["limit", "offset"],
    // `where` is unindexed; "condition"/"filter"/"clause" carry these queries.
    filter: ["filter", "condition"],
    filtering: ["filter", "condition"],
    predicate: ["condition", "filter"],
    condition: ["condition", "filter"],
    column: ["fields", "column"],
    columns: ["fields", "column"],
    projection: ["fields"],
    row: ["values"],
    rows: ["values"],

    // Schema and platform.
    table: ["table", "schema"],
    schema: ["schema", "table"],
    migration: ["migrate", "migration"],
    migrations: ["migrate", "migration"],
    ddl: ["migration", "table"],
    rls: ["rls", "policy"],
    policy: ["policy", "rls"],
    tenant: ["rls", "policy", "tenant"],
    auth: ["auth", "policy"],
    index: ["index"],
    transaction: ["begin", "commit", "rollback"],
    param: ["param"],
    params: ["param"],
    binding: ["param"],
    placeholder: ["param"],
    codegen: ["codegen", "typed"],
});

/**
 * Multi-word aliases, checked against the raw query before tokenisation
 * because tokenising destroys adjacency. Targets are single indexed tokens:
 * the index splits on underscores too, so "primary_key" is not a term and
 * expanding to it would match nothing.
 */
const PHRASE_ALIASES: [string, string[]][] = [
    ["on conflict", ["conflict", "add"]],
    ["order by", ["order"]],
    ["group by", ["group", "having"]],
    ["inner join", ["join", "inner"]],
    ["left join", ["join", "left"]],
    ["common table expression", ["cte", "recursive"]],
    ["row level security", ["rls", "policy"]],
    ["foreign key", ["references", "foreign"]],
    ["primary key", ["primary", "key"]],
    ["not null", ["null", "column"]],
    ["prepared statement", ["param", "prepared"]],
    ["where clause", ["condition", "clause", "filter"]],
];

/**
 * Expanded terms carry less weight than what the user actually typed, so an
 * alias can surface a document but cannot outrank a literal match.
 */
const EXPANSION_WEIGHT = 0.6;

/** Query terms with per-term weights, literal terms at 1.0. */
function expandQuery(query: string): Map<string, number> {
    const weighted = new Map<string, number>();
    const bump = (term: string, w: number) => {
        weighted.set(term, Math.max(weighted.get(term) ?? 0, w));
    };

    for (const term of tokenize(query)) bump(term, 1);

    const lowered = query.toLowerCase();
    for (const [phrase, targets] of PHRASE_ALIASES) {
        if (lowered.includes(phrase)) {
            for (const t of targets) bump(t, EXPANSION_WEIGHT);
        }
    }

    for (const term of tokenize(query)) {
        for (const t of ALIASES[term] ?? []) bump(t, EXPANSION_WEIGHT);
    }

    return weighted;
}

/* -------------------------------------------------------------------------- */
/* Scoring                                                                    */
/* -------------------------------------------------------------------------- */

const K1 = 1.2;
const B = 0.75;

interface Hit {
    idx: number;
    score: number;
}

interface SearchFilter {
    kind?: string[];
    area?: string[];
}

function passesFilter(idx: number, filter: SearchFilter): boolean {
    if (!VISIBLE_SET.has(idx)) return false;
    const chunk = CHUNKS[idx];
    if (filter.kind && filter.kind.length && !filter.kind.includes(chunk.kind)) return false;
    if (filter.area && filter.area.length && !filter.area.includes(chunk.area)) return false;
    return true;
}

/**
 * Okapi BM25, with each chunk's final score multiplied by its editorial weight
 * so a verified example beats a passing mention in prose at equal relevance.
 */
function scoreBm25(terms: Map<string, number>, filter: SearchFilter): Hit[] {
    const totals = new Map<number, number>();
    const n = INDEX.n || CHUNKS.length;

    for (const [term, termWeight] of terms) {
        const postings = POSTINGS[term];
        if (!postings) continue;

        const df = DF[term] ?? postings.length;
        // +1 inside the log keeps the idf non-negative for terms that appear in
        // more than half the corpus; a bare Robertson idf would go negative and
        // penalise documents for containing a common keyword like "get".
        const idf = Math.log(1 + (n - df + 0.5) / (df + 0.5));

        for (const [idx, tf] of postings) {
            if (!passesFilter(idx, filter)) continue;
            const len = INDEX.len[idx] || CHUNKS[idx].tokens || INDEX.avgLen;
            const norm = tf + K1 * (1 - B + (B * len) / INDEX.avgLen);
            const contribution = (idf * (tf * (K1 + 1))) / norm;
            totals.set(idx, (totals.get(idx) ?? 0) + contribution * termWeight);
        }
    }

    const hits: Hit[] = [];
    for (const [idx, raw] of totals) {
        hits.push({ idx, score: raw * (CHUNKS[idx].weight ?? 1) });
    }
    return hits;
}

/**
 * Fallback used when the index does not match the corpus. Substring counting is
 * far worse than BM25, but it is honest and keeps the server useful instead of
 * returning nothing after a partial regeneration.
 */
function scoreLiteral(terms: Map<string, number>, filter: SearchFilter): Hit[] {
    const hits: Hit[] = [];
    for (const idx of VISIBLE) {
        if (!passesFilter(idx, filter)) continue;
        const chunk = CHUNKS[idx];
        const haystack = (chunk.title + "\n" + chunk.content).toLowerCase();
        let score = 0;
        for (const [term, termWeight] of terms) {
            let from = 0;
            let count = 0;
            for (;;) {
                const at = haystack.indexOf(term, from);
                if (at === -1) break;
                count += 1;
                from = at + term.length;
                if (count > 20) break;
            }
            if (count) score += termWeight * (1 + Math.log(count));
        }
        if (score > 0) hits.push({ idx, score: score * (chunk.weight ?? 1) });
    }
    return hits;
}

function search(query: string, filter: SearchFilter, limit: number): Hit[] {
    const terms = expandQuery(query);
    if (terms.size === 0) return [];
    const hits = INDEX_USABLE ? scoreBm25(terms, filter) : scoreLiteral(terms, filter);
    hits.sort((a, b) => b.score - a.score || a.idx - b.idx);
    return hits.slice(0, limit);
}

/* -------------------------------------------------------------------------- */
/* Rendering helpers                                                          */
/* -------------------------------------------------------------------------- */

const SNIPPET_TOKENS = 200;
/** Hard cap on a single full-content chunk, so one huge page cannot blow the reply. */
const MAX_FULL_CHARS = 12000;

function locationOf(chunk: Chunk): string {
    const heading = chunk.headingPath && chunk.headingPath.length
        ? " > " + chunk.headingPath.join(" > ")
        : "";
    return chunk.path + heading;
}

/**
 * A window of roughly SNIPPET_TOKENS whitespace-separated words centred on the
 * first query-term hit, rather than the head of the chunk: the answer to a
 * specific question is usually in the middle of a section, and leading with the
 * section's preamble wastes the agent's context on boilerplate.
 */
function snippet(chunk: Chunk, terms: Map<string, number>): string {
    const words = chunk.content.split(/\s+/).filter((w) => w.length > 0);
    if (words.length <= SNIPPET_TOKENS) return chunk.content.trim();

    let hit = -1;
    outer: for (let i = 0; i < words.length; i += 1) {
        const normalized = words[i].toLowerCase().replace(/[^a-z0-9_]/g, "");
        if (!normalized) continue;
        for (const term of terms.keys()) {
            if (normalized.includes(term)) {
                hit = i;
                break outer;
            }
        }
    }

    // Bias the window to start slightly before the hit so the sentence that
    // introduces it survives.
    const start = hit < 0 ? 0 : Math.max(0, hit - 40);
    const end = Math.min(words.length, start + SNIPPET_TOKENS);
    const body = words.slice(start, end).join(" ");
    return (start > 0 ? "... " : "") + body + (end < words.length ? " ..." : "");
}

function fullContent(chunk: Chunk): string {
    if (chunk.content.length <= MAX_FULL_CHARS) return chunk.content;
    return (
        chunk.content.slice(0, MAX_FULL_CHARS) +
        "\n\n[truncated at " + MAX_FULL_CHARS + " characters - request a narrower section with qail_doc { path, section }]"
    );
}

function footer(extra?: string): string {
    const bits = [
        "qail " + qailVersion(),
        CHUNKS.length + " chunks indexed",
    ];
    if (!INDEX_USABLE) bits.push("DEGRADED: BM25 index out of sync with corpus, using literal matching");
    if (extra) bits.push(extra);
    return "\n---\n" + bits.join(" | ") +
        "\nLegacy paren schema syntax `table t ( ... )` is excluded from all results; QAIL schemas use the brace dialect.";
}

/* -------------------------------------------------------------------------- */
/* MCP envelopes (shape mirrors mcp/src/lib.rs tool_text / tool_error)         */
/* -------------------------------------------------------------------------- */

function toolText(text: string): unknown {
    return { content: [{ type: "text", text }], isError: false };
}

function toolError(message: string): unknown {
    return { content: [{ type: "text", text: message }], isError: true };
}

/* -------------------------------------------------------------------------- */
/* Corpus accessors                                                           */
/* -------------------------------------------------------------------------- */

function distinct(pick: (c: Chunk) => string): Map<string, number> {
    const counts = new Map<string, number>();
    for (const idx of VISIBLE) {
        const key = pick(CHUNKS[idx]);
        if (!key) continue;
        counts.set(key, (counts.get(key) ?? 0) + 1);
    }
    return counts;
}

const KINDS = distinct((c) => c.kind);
const AREAS = distinct((c) => c.area);

/** Kind names holding negative examples: inputs that fail, with the real error. */
function isInvalidKind(kind: string): boolean {
    return /invalid|negative|counter/i.test(kind);
}

/**
 * Only the executed QAIL-to-SQL pairs count as examples here.
 *
 * "example-code" is deliberately excluded: those chunks are Rust source from
 * core/examples/*.rs. They are excellent search results and useless as answers
 * to "show me a query", because an agent shown Rust when it asked for QAIL will
 * cheerfully write Rust.
 */
function isExampleKind(kind: string): boolean {
    return kind === "example";
}

/**
 * Grammar chunks name their production (`parse_where_clause`), but agents ask
 * for the construct (`where`). The exporter emits the construct in the chunk
 * body; fall back to deriving it from the production name so a schema tweak
 * upstream degrades instead of breaking.
 */
function constructOf(chunk: Chunk): string {
    const declared = /(?:^|\n)\s*(?:[-*]\s*)?construct:\s*([a-z0-9_]+)/i.exec(chunk.content);
    if (declared) return declared[1].toLowerCase();

    return chunk.title
        .toLowerCase()
        .trim()
        .replace(/^parse_/, "")
        .replace(/_(clause|command|strict)$/, "");
}

/**
 * The first QAIL line of an example chunk. Used to decide whether an example
 * "starts with" a construct, which is a much stronger signal than the construct
 * merely appearing somewhere in the body.
 */
function exampleInput(chunk: Chunk): string {
    const labelled = /(?:^|\n)\s*(?:input|qail):\s*(.+)/i.exec(chunk.content);
    if (labelled) return labelled[1].trim().replace(/^`|`$/g, "");

    for (const line of chunk.content.split("\n")) {
        const trimmed = line.trim().replace(/^`+|`+$/g, "");
        if (!trimmed) continue;
        if (trimmed.startsWith("#") || trimmed.startsWith("```")) continue;
        return trimmed;
    }
    return "";
}

/**
 * Resolve a user-supplied construct name into the candidate keys to match on.
 *
 * "on conflict" must reach the `on_conflict` production, and so must "conflict"
 * on its own, so the leading SQL filler word is stripped as a second candidate.
 */
function normalizeConstruct(name: string): string[] {
    const lowered = name.toLowerCase().trim().replace(/[^a-z0-9_ ]/g, "").replace(/\s+/g, "_");
    const out = new Set<string>();
    if (lowered) out.add(lowered);

    for (const alias of ALIASES[lowered] ?? ALIASES[lowered.replace(/_/g, " ")] ?? []) {
        out.add(alias);
    }

    const segments = lowered.split("_").filter((p) => p.length > 1);
    const meaningful = segments.filter((p) => !STOPWORDS.has(p));
    if (meaningful.length && meaningful.length < segments.length) {
        out.add(meaningful.join("_"));
        out.add(meaningful[meaningful.length - 1]);
    }

    return [...out];
}

/**
 * Segment-aware construct matching.
 *
 * Plain substring matching is wrong here and quietly so: `"merge_after_target"`
 * contains `"get"`, so asking for the `get` action used to return the MERGE
 * grammar. Matching whole underscore-separated segments keeps `conflict` ->
 * `on_conflict` and `join` -> `join_condition` working without that class of
 * accident.
 */
function constructMatches(key: string, candidate: string): boolean {
    if (key === candidate) return true;
    const keyParts = key.split("_");
    const candParts = candidate.split("_");
    if (candParts.every((p) => keyParts.includes(p))) return true;
    if (keyParts.every((p) => candParts.includes(p))) return true;
    return false;
}

/* -------------------------------------------------------------------------- */
/* Tool: qail_search                                                          */
/* -------------------------------------------------------------------------- */

function toolSearch(args: any): unknown {
    const query = typeof args?.query === "string" ? args.query.trim() : "";
    if (!query) {
        return toolError("qail_search requires a non-empty `query`. Example: { \"query\": \"how do I write an upsert\" }");
    }

    const limit = clampInt(args?.limit, 5, 1, 20);
    const snippetsOnly = args?.snippetsOnly !== false;
    const filter: SearchFilter = {
        kind: stringArray(args?.kind),
        area: stringArray(args?.area),
    };

    const unknownKinds = (filter.kind ?? []).filter((k) => !KINDS.has(k));
    const unknownAreas = (filter.area ?? []).filter((a) => !AREAS.has(a));

    const terms = expandQuery(query);
    const hits = search(query, filter, limit);

    if (hits.length === 0) {
        const notes: string[] = ["No matches for: " + query];
        if (unknownKinds.length) {
            notes.push("Unknown kind filter(s): " + unknownKinds.join(", ") + ". Available: " + [...KINDS.keys()].sort().join(", "));
        }
        if (unknownAreas.length) {
            notes.push("Unknown area filter(s): " + unknownAreas.join(", ") + ". Available: " + [...AREAS.keys()].sort().join(", "));
        }
        notes.push("Try qail_map for the repo layout, or qail_syntax with no arguments to list every grammar construct.");
        return toolText(notes.join("\n") + footer());
    }

    const lines: string[] = ["# qail_search: " + query, ""];
    hits.forEach((hit, rank) => {
        const chunk = CHUNKS[hit.idx];
        lines.push("## " + (rank + 1) + ". " + chunk.title);
        lines.push(
            "id: " + chunk.id +
            " | path: " + locationOf(chunk) +
            " | kind: " + chunk.kind +
            " | area: " + chunk.area +
            " | " + chunk.tokens + " tokens" +
            " | score " + hit.score.toFixed(2),
        );
        lines.push("");
        lines.push(snippetsOnly ? snippet(chunk, terms) : fullContent(chunk));
        lines.push("");
    });

    if (snippetsOnly) {
        lines.push("Fetch any result in full with qail_doc { \"id\": \"<id>\" }.");
    }

    return toolText(lines.join("\n") + footer());
}

/* -------------------------------------------------------------------------- */
/* Tool: qail_doc                                                             */
/* -------------------------------------------------------------------------- */

/**
 * Path matching is deliberately forgiving. Agents cite documents by basename
 * ("quickstart.md") far more often than by the full repo-relative path, and a
 * strict match would turn a recoverable near-miss into a dead end.
 */
function resolvePath(path: string): number[] {
    const wanted = path.toLowerCase().replace(/^\.?\//, "");
    const exact = VISIBLE.filter((i) => CHUNKS[i].path.toLowerCase() === wanted);
    if (exact.length) return exact;

    const suffix = VISIBLE.filter((i) => CHUNKS[i].path.toLowerCase().endsWith(wanted));
    if (suffix.length) return suffix;

    return VISIBLE.filter((i) => CHUNKS[i].path.toLowerCase().includes(wanted));
}

function toolDoc(args: any): unknown {
    const id = typeof args?.id === "string" ? args.id.trim() : "";
    const path = typeof args?.path === "string" ? args.path.trim() : "";
    const section = typeof args?.section === "string" ? args.section.trim().toLowerCase() : "";
    const outline = args?.outline === true;

    if (!id && !path) {
        return toolError(
            "qail_doc needs either `id` (from a qail_search result) or `path` (a repo-relative doc path, e.g. \"docs/src/reference/queries.md\").\n" +
            "To discover either: call qail_search, or qail_map for the documentation tree.",
        );
    }

    let indices: number[];
    let label: string;

    if (id) {
        indices = VISIBLE.filter((i) => CHUNKS[i].id === id);
        label = "id " + id;
        if (indices.length === 0) {
            const known = CHUNKS.some((c) => c.id === id);
            return toolError(
                known
                    ? "Chunk " + id + " exists but teaches the legacy paren schema dialect and is intentionally not served. Use qail://core/schema-reference for the current brace dialect."
                    : "No chunk with id " + id + ". Ids come from qail_search results and are not guessable; run qail_search first.",
            );
        }
    } else {
        indices = resolvePath(path);
        label = "path " + path;
        if (indices.length === 0) {
            return toolError(
                "No document matched path " + path + ". Paths are repo-relative (\"docs/src/...\", \"core/README.md\"). " +
                "Call qail_map for the documentation tree or qail_search to locate the topic.",
            );
        }
    }

    if (section) {
        const narrowed = indices.filter((i) => {
            const chunk = CHUNKS[i];
            const hay = (chunk.title + " " + (chunk.headingPath ?? []).join(" ")).toLowerCase();
            return hay.includes(section);
        });
        if (narrowed.length === 0) {
            const available = indices
                .map((i) => CHUNKS[i].title)
                .filter((t, n, all) => all.indexOf(t) === n)
                .slice(0, 40);
            return toolError(
                "No section matching \"" + section + "\" in " + label + ". Sections present: " + available.join(" | "),
            );
        }
        indices = narrowed;
    }

    // Preserve corpus order so a multi-chunk document reads top to bottom.
    indices.sort((a, b) => a - b);

    if (outline) {
        const lines: string[] = ["# Outline: " + label, ""];
        let totalTokens = 0;

        // A basename like "quickstart.md" can resolve to more than one file.
        // Interleaving their headings by corpus order produces an outline that
        // reads as one incoherent document, so group under an explicit path.
        const paths = [...new Set(indices.map((i) => CHUNKS[i].path))];
        for (const path of paths) {
            if (paths.length > 1) lines.push("## " + path);
            for (const i of indices.filter((n) => CHUNKS[n].path === path)) {
                const chunk = CHUNKS[i];
                const depth = (chunk.headingPath ?? []).length;
                totalTokens += chunk.tokens;
                lines.push(
                    "  ".repeat(depth) + "- " + chunk.title +
                    "  (" + chunk.tokens + " tokens, id: " + chunk.id + ")",
                );
            }
            if (paths.length > 1) lines.push("");
        }
        lines.push("");
        lines.push(
            indices.length + " chunk" + (indices.length === 1 ? "" : "s") +
            (paths.length > 1 ? " across " + paths.length + " files" : "") +
            ", " + totalTokens + " tokens total.",
        );
        lines.push("Fetch one with qail_doc { \"id\": \"<id>\" }, or a subtree with qail_doc { \"path\": \"...\", \"section\": \"<heading>\" }.");
        return toolText(lines.join("\n") + footer());
    }

    const lines: string[] = [];
    for (const i of indices) {
        const chunk = CHUNKS[i];
        lines.push("# " + chunk.title);
        lines.push("id: " + chunk.id + " | path: " + locationOf(chunk) + " | kind: " + chunk.kind + " | area: " + chunk.area);
        lines.push("");
        lines.push(fullContent(chunk));
        lines.push("");
    }

    // A whole-document fetch can be enormous; nudge toward the outline instead.
    const tokens = indices.reduce((sum, i) => sum + CHUNKS[i].tokens, 0);
    const hint = tokens > 6000
        ? "This document is " + tokens + " tokens. Next time call qail_doc { \"outline\": true } first and fetch only the section you need."
        : undefined;

    return toolText(lines.join("\n") + footer(hint));
}

/* -------------------------------------------------------------------------- */
/* Tool: qail_syntax                                                          */
/* -------------------------------------------------------------------------- */

function productionIndices(): number[] {
    return VISIBLE.filter((i) => CHUNKS[i].kind === "production");
}

function toolSyntax(args: any): unknown {
    const requested = typeof args?.construct === "string" ? args.construct.trim() : "";
    const wantExamples = clampInt(args?.examples, 3, 0, 10);
    const productions = productionIndices();

    if (!requested) {
        const byConstruct = new Map<string, number>();
        for (const i of productions) {
            const key = constructOf(CHUNKS[i]);
            byConstruct.set(key, (byConstruct.get(key) ?? 0) + 1);
        }
        const names = [...byConstruct.keys()].sort();
        const lines = [
            "# QAIL grammar constructs (" + names.length + ")",
            "",
            "Actions: get (SELECT), add (INSERT), set (UPDATE), del (DELETE), merge (MERGE).",
            "Also: with (CTE), export, and begin / commit / rollback for transactions.",
            "",
            "Call qail_syntax { \"construct\": \"<name>\" } for the grammar card and verified examples.",
            "SQL names work too: \"select\", \"insert\", \"on conflict\" are aliased onto the QAIL keyword.",
            "",
        ];
        for (const name of names) {
            const count = byConstruct.get(name) ?? 0;
            lines.push("- " + name + (count > 1 ? "  (" + count + " productions)" : ""));
        }
        return toolText(lines.join("\n") + footer());
    }

    const candidates = normalizeConstruct(requested);
    const matched: number[] = [];
    for (const i of productions) {
        const key = constructOf(CHUNKS[i]);
        if (candidates.some((c) => constructMatches(key, c))) matched.push(i);
    }

    if (matched.length === 0) {
        // Fall back to retrieval rather than a bare "not found": the agent's
        // word for the construct may simply not be in the alias map.
        const fallback = search(requested, { kind: ["production"] }, 5);
        if (fallback.length === 0) {
            return toolError(
                "No grammar construct matched \"" + requested + "\". " +
                "Call qail_syntax with no arguments to list every construct.",
            );
        }
        matched.push(...fallback.map((h) => h.idx));
    }

    // Exact construct matches first; partials afterwards.
    matched.sort((a, b) => {
        const rank = (i: number) => (candidates.includes(constructOf(CHUNKS[i])) ? 0 : 1);
        return rank(a) - rank(b) || a - b;
    });

    const lines: string[] = ["# Syntax: " + requested, ""];
    for (const i of matched.slice(0, 8)) {
        const chunk = CHUNKS[i];
        lines.push("## " + chunk.title + "  (construct: " + constructOf(chunk) + ")");
        lines.push("source: " + chunk.path + " | id: " + chunk.id);
        lines.push("");
        lines.push(fullContent(chunk));
        lines.push("");
    }

    if (wantExamples > 0) {
        const examples = examplesForConstruct(candidates, wantExamples);
        lines.push("## Verified examples");
        if (examples.length === 0) {
            lines.push(
                "None of the verified examples exercise this construct. " +
                "Every example in the corpus was actually run through the parser and transpiler, so absence means untested here, not unsupported. " +
                "Confirm a candidate snippet with qail_parse_query.",
            );
        } else {
            for (const i of examples) {
                lines.push("");
                lines.push(CHUNKS[i].content.trim());
            }
        }
        lines.push("");
    }

    return toolText(lines.join("\n") + footer());
}

/**
 * Rank verified examples for a construct: an example whose QAIL input *starts*
 * with the construct demonstrates it; one that merely mentions it somewhere is
 * a weaker illustration.
 */
function examplesForConstruct(candidates: string[], limit: number): number[] {
    const scored: { idx: number; rank: number }[] = [];
    for (const i of VISIBLE) {
        if (!isExampleKind(CHUNKS[i].kind)) continue;
        const input = exampleInput(CHUNKS[i]).toLowerCase();
        if (!input) continue;

        let rank = 0;
        for (const c of candidates) {
            const word = c.replace(/_/g, " ");
            if (input.startsWith(c) || input.startsWith(word)) {
                rank = Math.max(rank, 2);
            } else if (input.includes(c) || input.includes(word)) {
                rank = Math.max(rank, 1);
            }
        }
        if (rank > 0) scored.push({ idx: i, rank });
    }
    // Shortest first within a rank. The corpus contains both "get users" and a
    // comment-escaping torture case for the same construct; the agent should be
    // shown the canonical form before the edge case.
    scored.sort((a, b) => b.rank - a.rank || CHUNKS[a.idx].tokens - CHUNKS[b.idx].tokens || a.idx - b.idx);
    return scored.slice(0, limit).map((s) => s.idx);
}

/* -------------------------------------------------------------------------- */
/* Tool: qail_examples                                                        */
/* -------------------------------------------------------------------------- */

function toolExamples(args: any): unknown {
    const query = typeof args?.query === "string" ? args.query.trim() : "";
    const construct = typeof args?.construct === "string" ? args.construct.trim() : "";
    const polarityRaw = typeof args?.polarity === "string" ? args.polarity.toLowerCase() : "valid";
    const polarity = ["valid", "invalid", "both"].includes(polarityRaw) ? polarityRaw : "valid";
    const limit = clampInt(args?.limit, 5, 1, 20);

    const validKinds = [...KINDS.keys()].filter((k) => isExampleKind(k));
    const invalidKinds = [...KINDS.keys()].filter((k) => isInvalidKind(k));

    const sections: string[] = [];

    const collect = (kinds: string[], want: number): number[] => {
        if (kinds.length === 0 || want <= 0) return [];
        if (query) return search(query, { kind: kinds }, want).map((h) => h.idx);
        if (construct) {
            const picked = examplesForConstruct(normalizeConstruct(construct), want).filter((i) =>
                kinds.includes(CHUNKS[i].kind),
            );
            if (picked.length) return picked;
            // examplesForConstruct only ranks positive examples; for the
            // negative corpus fall through to a plain construct search.
            return search(construct, { kind: kinds }, want).map((h) => h.idx);
        }
        return VISIBLE.filter((i) => kinds.includes(CHUNKS[i].kind)).slice(0, want);
    };

    if (polarity === "valid" || polarity === "both") {
        const hits = collect(validKinds, limit);
        sections.push("## Verified examples (parsed and transpiled by the real pipeline)");
        sections.push(
            hits.length
                ? hits.map((i) => CHUNKS[i].content.trim() + "\n(id: " + CHUNKS[i].id + ")").join("\n\n")
                : "No verified example matched. Every example in this corpus was executed, so the set is exact rather than exhaustive — verify a candidate with qail_parse_query.",
        );
    }

    if (polarity === "invalid" || polarity === "both") {
        const hits = collect(invalidKinds, limit);
        sections.push("## Negative examples (real parser / transpiler output)");
        sections.push(
            hits.length
                ? hits.map((i) => CHUNKS[i].content.trim() + "\n(id: " + CHUNKS[i].id + ")").join("\n\n")
                : "No negative example matched. The negative corpus is small and covers specific known traps only.",
        );
    }

    const header = "# qail_examples" +
        (query ? ": " + query : "") +
        (construct ? " [construct: " + construct + "]" : "") +
        " [polarity: " + polarity + "]";

    return toolText(header + "\n\n" + sections.join("\n\n") + footer());
}

/* -------------------------------------------------------------------------- */
/* Tool: qail_map                                                             */
/* -------------------------------------------------------------------------- */

/**
 * Hand-written because a corpus cannot describe itself: the descriptions below
 * are the crates' own Cargo.toml `description` fields, condensed. The
 * per-area chunk counts underneath are computed, so the map stays honest about
 * what is actually retrievable even as the corpus grows.
 */
const CRATE_MAP: [string, string][] = [
    ["core", "AST kernel. Parser, transpiler, formatter, optimizer, RLS context, access policy, schema handling, migrations, typed codegen."],
    ["pg", "PostgreSQL driver. Executes the typed AST over the wire protocol directly."],
    ["gateway", "Access gateway. Schema-driven AutoREST, WebSocket, OpenAPI, RLS and policy enforcement."],
    ["qdrant", "Vector bridge. Qdrant search driver with AST-compatible filters."],
    ["workflow", "Flow engine. Declarative state-machine workflows with waits, retries, side-effect checkpoints."],
    ["workflow-postgres", "Flow ledger. PostgreSQL storage for workflow state, leases, idempotency, timeouts."],
    ["encoder", "Encoder ABI. Lightweight protocol and query encoding for non-Rust transports."],
    ["cli", "SchemaOps CLI. Schema pull, drift diff, phased migrations, lint, AST query tooling."],
    ["lsp", "Language Server Protocol implementation for QAIL."],
    ["mcp", "This MCP server's dispatch logic: tools, resources, prompts."],
    ["wasm", "WebAssembly build of the MCP server, which is what this endpoint runs."],
    ["codegen", "Rust AST to Zig type definition generator."],
    ["sdk/", "Client SDKs: dart, typescript, swift, kotlin."],
];

/** Where the subsystems an agent asks about actually live. */
const SUBSYSTEM_MAP: [string, string][] = [
    ["query parsing", "core/src/parser/ (grammar/ holds one file per clause family)"],
    ["SQL generation", "core/src/transpiler/"],
    ["migrations", "core/src/migrate/ - brace schema dialect, driven by parse_qail"],
    ["typed codegen", "core/src/build/ - brace dialect too, plus ref: and protected"],
    ["legacy paren schema", "core/src/parser/schema.rs - used only by cli migrations/backup; do not write new schemas in it"],
    ["RLS and policy", "core/src/rls/, core/src/access/, enforced in gateway"],
    ["formatter", "core/src/fmt/"],
    ["optimizer / analyzer", "core/src/optimizer/, core/src/analyzer/"],
    ["canonical schema sample", "examples/schema/single/schema.qail"],
];

function toolMap(args: any): unknown {
    const area = typeof args?.area === "string" ? args.area.trim().toLowerCase() : "";

    if (area) {
        const indices = VISIBLE.filter((i) => CHUNKS[i].area.toLowerCase() === area);
        if (indices.length === 0) {
            return toolError(
                "Unknown area \"" + area + "\". Areas in the corpus: " + [...AREAS.keys()].sort().join(", "),
            );
        }
        const byPath = new Map<string, number>();
        for (const i of indices) byPath.set(CHUNKS[i].path, (byPath.get(CHUNKS[i].path) ?? 0) + 1);

        const lines = ["# Area: " + area, "", indices.length + " chunks across " + byPath.size + " documents.", ""];
        for (const [path, count] of [...byPath.entries()].sort()) {
            lines.push("- " + path + "  (" + count + " chunk" + (count === 1 ? "" : "s") + ")");
        }
        lines.push("");
        lines.push("Fetch any of these with qail_doc { \"path\": \"...\", \"outline\": true }.");
        return toolText(lines.join("\n") + footer());
    }

    const lines: string[] = [
        "# qail.rs repository map",
        "",
        "QAIL is a typed query AST with its own surface syntax. A query is parsed into the AST,",
        "validated against a schema, and transpiled to SQL; nothing here executes a database call.",
        "",
        "## Crates",
    ];
    for (const [name, desc] of CRATE_MAP) lines.push("- " + name + " - " + desc);

    lines.push("");
    lines.push("## Where subsystems live");
    for (const [what, whereAt] of SUBSYSTEM_MAP) lines.push("- " + what + ": " + whereAt);

    lines.push("");
    lines.push("## Indexed documentation");
    for (const [name, count] of [...AREAS.entries()].sort((a, b) => b[1] - a[1])) {
        lines.push("- " + name + ": " + count + " chunk" + (count === 1 ? "" : "s"));
    }

    lines.push("");
    lines.push("## Chunk kinds (use as the `kind` filter on qail_search)");
    for (const [name, count] of [...KINDS.entries()].sort((a, b) => b[1] - a[1])) {
        lines.push("- " + name + ": " + count);
    }

    lines.push("");
    lines.push("## Routing");
    lines.push("- prose question -> qail_search, then qail_doc for the full section");
    lines.push("- \"what is the syntax for X\" -> qail_syntax { construct: \"X\" }");
    lines.push("- \"show me a working query\" -> qail_examples");
    lines.push("- \"is this snippet valid\" -> qail_parse_query / qail_transpile_query (they run the real parser)");

    return toolText(lines.join("\n") + footer());
}

/* -------------------------------------------------------------------------- */
/* Argument coercion                                                          */
/* -------------------------------------------------------------------------- */

function clampInt(value: unknown, fallback: number, min: number, max: number): number {
    const n = typeof value === "number" ? value : typeof value === "string" ? Number(value) : NaN;
    if (!Number.isFinite(n)) return fallback;
    return Math.min(max, Math.max(min, Math.trunc(n)));
}

/** Accepts an array or a single string, because clients disagree about both. */
function stringArray(value: unknown): string[] | undefined {
    if (typeof value === "string" && value.trim()) return [value.trim()];
    if (!Array.isArray(value)) return undefined;
    const out = value.filter((v): v is string => typeof v === "string" && v.trim().length > 0);
    return out.length ? out : undefined;
}

/* -------------------------------------------------------------------------- */
/* Tool definitions                                                           */
/* -------------------------------------------------------------------------- */

/** Every tool here is a pure read over a baked-in bundle, hence the annotations. */
const READ_ONLY = {
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
};

export const KNOWLEDGE_TOOLS: unknown[] = [
    {
        name: "qail_search",
        title: "Search QAIL Documentation",
        description:
            "Full-text search across the QAIL documentation, crate READMEs, grammar productions and verified examples. " +
            "Start here for any 'how do I ...' question. SQL vocabulary is accepted: select/insert/update/delete/upsert are mapped onto QAIL's get/add/set/del/conflict.",
        inputSchema: {
            type: "object",
            properties: {
                query: {
                    type: "string",
                    description: "Natural-language or keyword query, e.g. \"how do I write an upsert\" or \"row level security policy\".",
                },
                kind: {
                    type: "array",
                    items: { type: "string" },
                    description: "Restrict to chunk kinds, e.g. [\"example\"] or [\"production\"]. Call qail_map for the full list.",
                },
                area: {
                    type: "array",
                    items: { type: "string" },
                    description: "Restrict to subsystem areas, e.g. [\"core\"], [\"gateway\"], [\"sdk\"].",
                },
                limit: {
                    type: "integer",
                    default: 5,
                    minimum: 1,
                    maximum: 20,
                    description: "Number of results.",
                },
                snippetsOnly: {
                    type: "boolean",
                    default: true,
                    description: "Return ~200-token snippets instead of full chunks. Keep true and follow up with qail_doc.",
                },
            },
            required: ["query"],
            additionalProperties: false,
        },
        annotations: READ_ONLY,
    },
    {
        name: "qail_doc",
        title: "Read QAIL Documentation",
        description:
            "Fetch a documentation chunk in full by id (from a qail_search result) or by repo-relative path. " +
            "Use outline:true first on anything large - it returns the heading tree with token counts so you can fetch only the section you need.",
        inputSchema: {
            type: "object",
            properties: {
                id: { type: "string", description: "Chunk id, as printed by qail_search." },
                path: { type: "string", description: "Repo-relative path, e.g. \"docs/src/reference/queries.md\" or \"core/README.md\". A basename is accepted." },
                section: { type: "string", description: "Case-insensitive heading filter within the document." },
                outline: { type: "boolean", default: false, description: "Return the heading tree and token counts instead of the content." },
            },
            additionalProperties: false,
        },
        annotations: READ_ONLY,
    },
    {
        name: "qail_syntax",
        title: "QAIL Grammar Construct",
        description:
            "Grammar card for a QAIL construct (where, join, with, conflict, order, fields, ...) taken from the parser source, plus verified examples that use it. " +
            "Call with no arguments to list every construct.",
        inputSchema: {
            type: "object",
            properties: {
                construct: {
                    type: "string",
                    description: "Construct or keyword, e.g. \"where\", \"on conflict\", \"with\", \"join\". SQL names are aliased. Omit to list all constructs.",
                },
                examples: {
                    type: "integer",
                    default: 3,
                    minimum: 0,
                    maximum: 10,
                    description: "How many verified examples to append.",
                },
            },
            additionalProperties: false,
        },
        annotations: READ_ONLY,
    },
    {
        name: "qail_examples",
        title: "QAIL Query Examples",
        description:
            "Working QAIL queries paired with the SQL they actually transpile to, and - with polarity \"invalid\" or \"both\" - inputs that fail, together with the real parser error. " +
            "Every example was executed through the parser and transpiler, so the pairs are known-correct rather than illustrative.",
        inputSchema: {
            type: "object",
            properties: {
                query: { type: "string", description: "Free-text query to rank examples against." },
                construct: { type: "string", description: "Restrict to examples exercising this construct, e.g. \"join\", \"order\"." },
                polarity: {
                    type: "string",
                    enum: ["valid", "invalid", "both"],
                    default: "valid",
                    description: "\"invalid\" returns known-bad inputs with their real error text.",
                },
                limit: { type: "integer", default: 5, minimum: 1, maximum: 20, description: "Examples per polarity." },
            },
            additionalProperties: false,
        },
        annotations: READ_ONLY,
    },
    {
        name: "qail_map",
        title: "QAIL Repository Map",
        description:
            "Repository orientation: what each crate does, where each subsystem lives, which documentation areas are indexed, and which tool answers which question shape. " +
            "Call this first when you do not know where to look.",
        inputSchema: {
            type: "object",
            properties: {
                area: { type: "string", description: "Drill into one area and list its documents instead of the whole map." },
            },
            additionalProperties: false,
        },
        annotations: READ_ONLY,
    },
];

const TOOL_NAMES = new Set(KNOWLEDGE_TOOLS.map((t) => (t as { name: string }).name));

/* -------------------------------------------------------------------------- */
/* Resources                                                                  */
/* -------------------------------------------------------------------------- */

/**
 * These three are in-bundle strings rather than corpus lookups on purpose:
 * they are the first thing a client loads and they must never depend on
 * retrieval quality.
 *
 * Every QAIL line below is either copied verbatim from
 * docs/generated/verified-examples.json / examples/schema/single/schema.qail, or
 * was independently executed against the real parser and transpiler. Nothing in
 * this file is covered by the knowledge_export lint, which walks only ```qail
 * fences under docs/ — so any edit here MUST be re-checked by hand, through
 * qail_parse_query or a scratch example against qail-core.
 *
 * No backticks or code fences below: the whole file is TypeScript, and prose
 * that cannot accidentally terminate a template literal is prose that cannot
 * silently corrupt the bundle.
 */

const ORIENTATION = [
    "# QAIL orientation",
    "",
    "QAIL is a typed query AST with its own surface syntax, implemented in Rust in the qail.rs",
    "workspace. You write a QAIL query; the parser produces a typed AST; the transpiler emits SQL.",
    "This server never touches a database - every tool is a read over source-derived data.",
    "",
    "## The five actions",
    "",
    "  get    -> SELECT",
    "  add    -> INSERT",
    "  set    -> UPDATE",
    "  del    -> DELETE",
    "  merge  -> MERGE",
    "",
    "Plus: with (CTE, optionally recursive), export (a SELECT intended for extraction),",
    "and begin / commit / rollback for transactions.",
    "",
    "## Crate topology",
    "",
    "  core               AST kernel: parser, transpiler, formatter, optimizer, RLS, policy, migrate, build",
    "  pg                 PostgreSQL driver executing the typed AST over the wire protocol",
    "  gateway            AutoREST, WebSocket, OpenAPI, RLS and policy enforcement",
    "  qdrant             Qdrant vector driver with AST-compatible filters",
    "  workflow           Declarative state-machine workflows; workflow-postgres is its ledger",
    "  encoder            Protocol and query encoding for non-Rust transports",
    "  cli                Schema pull, drift diff, phased migrations, lint",
    "  lsp                Language server",
    "  mcp / wasm         This server, and its WebAssembly build",
    "  sdk/               dart, typescript, swift, kotlin clients",
    "",
    "## Which tool answers which question",
    "",
    "  \"how do I ...\", any prose question      -> qail_search, then qail_doc for the full section",
    "  \"what is the syntax for X\"              -> qail_syntax { construct: \"X\" }",
    "  \"show me a working query\"               -> qail_examples",
    "  \"what breaks / what is invalid\"         -> qail_examples { polarity: \"invalid\" }",
    "  \"where does X live in the repo\"         -> qail_map",
    "  \"is THIS snippet valid\"                 -> qail_parse_query or qail_transpile_query",
    "  \"format THIS snippet\"                   -> qail_format_query",
    "",
    "Never assert that a snippet is valid from documentation alone. qail_parse_query runs the real",
    "parser; documentation describes intent, the parser is the authority.",
    "",
    "## The schema-dialect warning (read before writing any schema)",
    "",
    "Three schema parsers exist in this repo and they do NOT accept the same input.",
    "",
    "  1. core/src/parser/schema.rs   PAREN dialect:  table users ( id uuid primary_key, ... )",
    "                                 LEGACY. Used only by the CLI's migration and backup paths.",
    "                                 Never write new schemas in it. This server excludes it from",
    "                                 all search results.",
    "  2. core/src/migrate/parser.rs  BRACE dialect. Drives MIGRATIONS.",
    "  3. core/src/build/schema.rs    BRACE dialect. Drives TYPED CODEGEN. Accepts two extras that",
    "                                 the migrate parser rejects: ref:table.column and protected.",
    "",
    "So a schema block can be valid for one brace parser and rejected by the other. Read",
    "qail://core/schema-reference before writing one.",
    "",
    "## Limits",
    "",
    "  Parser input cap: 65536 bytes (MAX_INPUT_LENGTH).",
    "  Comments are stripped before parsing, including inside otherwise-quoted-looking text.",
].join("\n");

const CHEATSHEET = [
    "# QAIL cheatsheet",
    "",
    "Every query below was executed through the real parser and transpiler; the SQL shown is what",
    "the transpiler actually emitted. Source: docs/generated/verified-examples.json.",
    "",
    "## Actions",
    "",
    "  get = SELECT    add = INSERT    set = UPDATE    del = DELETE    merge = MERGE",
    "  with = CTE      export = extraction SELECT      begin / commit / rollback = transaction",
    "",
    "## Clause order",
    "",
    "  get <table> [join ...] [fields ...] [where ...] [having ...]",
    "             [order by ...] [limit N] [offset N]",
    "",
    "QAIL has NO group by clause. There is no group-by production in the grammar, and any",
    "trailing 'group by ...' is a parse error. Grouping is reachable only through the builder",
    "API's group_by_mode, never through the surface syntax.",
    "",
    "having currently accepts only a non-aggregate left-hand side. An aggregate there parses but",
    "transpiles to an embedded /* ERROR: Invalid condition expression */ comment rather than",
    "failing, so always run a having query through qail_transpile_query before trusting it.",
    "",
    "fields may appear after a join, as in the join examples below. Strings use double quotes;",
    "single quotes also parse, and doubling a quote escapes it.",
    "",
    "## Canonical forms",
    "",
    "  get users",
    "    -> SELECT * FROM users",
    "",
    "  get users fields id, email",
    "    -> SELECT id, email FROM users",
    "",
    "  get users fields * where active = true",
    "    -> SELECT * FROM users WHERE active = true",
    "",
    "  get users fields * where active = true and role = \"admin\"",
    "    -> SELECT * FROM users WHERE active = true AND role = 'admin'",
    "",
    "  get users fields * where active = true or role = \"admin\"",
    "    -> SELECT * FROM users WHERE (active = true OR role = 'admin')",
    "       (OR chains are parenthesised; AND chains are not)",
    "",
    "  get users fields id where email = $1",
    "    -> SELECT id FROM users WHERE email = $1",
    "",
    "  get users fields id where id in :ids",
    "    -> SELECT id FROM users WHERE id = ANY(:ids)",
    "",
    "  get users fields id where id not in :blocked_ids",
    "    -> SELECT id FROM users WHERE id != ALL(:blocked_ids)",
    "",
    "  get users fields id where name ~ \"john\"",
    "    -> SELECT id FROM users WHERE name ILIKE '%john%'",
    "       (~ is case-insensitive contains, not a regex)",
    "",
    "  get users fields * where metadata.theme = \"dark\"",
    "    -> SELECT * FROM users WHERE metadata->>'theme' = 'dark'",
    "       (dotted paths become JSON text extraction)",
    "",
    "  get docs fields id where metadata @> {\"tags\":[\"a\",{\"b\":true}],\"n\":1}",
    "    -> SELECT id FROM docs WHERE metadata @> '{\"tags\":[\"a\",{\"b\":true}],\"n\":1}'::jsonb",
    "",
    "  get subscriptions fields id where age = 6mo",
    "    -> SELECT id FROM subscriptions WHERE age = INTERVAL '6 months'",
    "       (interval shorthand: 30m 24h 7d 1w 6mo 1y)",
    "",
    "  get users fields * order by created_at desc",
    "    -> SELECT * FROM users ORDER BY created_at DESC",
    "       (a bare order by column defaults to ASC)",
    "",
    "  get users fields * limit 10 offset 20",
    "    -> SELECT * FROM users LIMIT 10 OFFSET 20",
    "",
    "  get users fields id, name, email where active = true order by created_at desc limit 10",
    "    -> SELECT id, name, email FROM users WHERE active = true ORDER BY created_at DESC LIMIT 10",
    "",
    "  get users join posts on users.id = posts.user_id fields id, title",
    "    -> SELECT id, title FROM users LEFT JOIN posts ON users.id = posts.user_id",
    "       WATCH OUT: a bare join is a LEFT JOIN, not an INNER JOIN.",
    "",
    "  get users inner join posts on users.id = posts.user_id fields id, title",
    "    -> SELECT id, title FROM users INNER JOIN posts ON users.id = posts.user_id",
    "",
    "  get orders right join customers on orders.customer_id = customers.id",
    "    -> SELECT * FROM orders RIGHT JOIN customers ON orders.customer_id = customers.id",
    "",
    "  set users values name = \"John\", active = true where id = $1",
    "    -> UPDATE users SET name = 'John', active = true WHERE id = $1",
    "",
    "  del sessions where expired_at < $1",
    "    -> DELETE FROM sessions WHERE expired_at < $1",
    "",
    "  export users fields id, email where active = true limit 100",
    "    -> SELECT id, email FROM users WHERE active = true LIMIT 100",
    "",
    "  begin  /  commit  /  rollback",
    "    -> BEGIN TRANSACTION;  /  COMMIT;  /  ROLLBACK;",
    "",
    "  session set app.current_tenant_id = 'tenant-1'",
    "    -> SET app.current_tenant_id = 'tenant-1'",
    "",
    "## Shorthand",
    "",
    "  get users[active = true]  desugars to a where clause",
    "    (desugar_bracket_filter, core/src/parser/grammar/mod.rs)",
    "",
    "## Inserts and upserts",
    "",
    "The corpus has no verified transpile pair for add, so no SQL is claimed here. The grammar",
    "productions give the shape:",
    "",
    "  add <table> values <v1>, <v2>",
    "  add <table> values ... conflict (col) nothing",
    "  add <table> values ... conflict (col) update other = <value>",
    "",
    "Confirm any add you write with qail_parse_query before relying on it - qail_examples with",
    "polarity \"invalid\" shows add forms that parse but transpile to broken SQL.",
].join("\n");

const SCHEMA_REFERENCE = [
    "# QAIL schema reference (brace dialect)",
    "",
    "## Read this first: there are two brace parsers",
    "",
    "A .qail schema file is consumed by two different parsers, and they accept slightly different",
    "input. Neither is a superset of the other in practice, so a block that compiles in one context",
    "can fail in the other.",
    "",
    "  core/src/migrate/parser.rs   parse_qail    drives MIGRATIONS",
    "  core/src/build/schema.rs     Schema::parse drives TYPED CODEGEN",
    "",
    "The codegen parser additionally accepts two things the migrate parser rejects:",
    "",
    "  ref:table.column   foreign-key shorthand",
    "  protected          column option",
    "",
    "Those are valid QAIL - they are simply codegen-only. If a schema must feed both, express",
    "relationships with the long form (references) and leave protected out.",
    "",
    "A third parser exists - core/src/parser/schema.rs, the PAREN dialect, table users ( ... ) -",
    "but it is legacy and used only by the CLI's migration and backup paths. Do not write it, and",
    "do not translate examples into it. This server withholds it from all search results.",
    "",
    "## Shape",
    "",
    "A table block is brace-delimited and newline-separated. There are NO commas between columns.",
    "",
    "Verbatim from examples/schema/single/schema.qail, which is the canonical sample and defines",
    "the tenants table this block references:",
    "",
    "  table users {",
    "    id uuid primary_key default gen_random_uuid()",
    "    tenant_id uuid not_null references tenants(id) on_delete cascade",
    "    email text unique not_null",
    "    full_name text not_null",
    "    role text not_null default 'member'",
    "    created_at timestamptz not_null default now()",
    "    enable_rls",
    "    force_rls",
    "  }",
    "",
    "That file also shows the index forms, which sit at file level, outside any table block:",
    "",
    "  unique index idx_users_tenant_email on users (tenant_id,email)",
    "  index idx_bookings_tenant_date on bookings (tenant_id,travel_date)",
    "",
    "## Column options accepted by the migrate parser",
    "",
    "  primary_key",
    "  unique",
    "  not_null",
    "  default <expr>",
    "  references <table>(<column>) [on_delete cascade]",
    "",
    "## Table-level and file-level directives (migrate parser)",
    "",
    "  enable_rls",
    "  force_rls",
    "  extension \"name\"",
    "  index / unique index",
    "",
    "## Codegen-only additions",
    "",
    "  author_id uuid ref:users.id      shorthand for a foreign key",
    "  password_hash text protected",
    "",
    "The type is mandatory and comes first: column_name TYPE [constraints] [ref:t.c] [protected].",
    "Dropping the type - writing author_id ref:users.id - is rejected by BOTH brace parsers.",
    "",
    "## The mistake everyone makes",
    "",
    "  default(true)    INVALID in all three parsers",
    "  default true     correct",
    "",
    "The value follows the keyword; it is not a call. The same goes for the other options -",
    "they are bare keywords, not functions.",
    "",
    "## Verifying",
    "",
    "This server cannot run the schema parsers. To check a schema, run the CLI against it, or use",
    "qail_search over the migration documentation for the workflow (author deltas in db/, then pull).",
].join("\n");

/** Null-prototype so an unknown uri such as "constructor" reads as undefined. */
const RESOURCE_BODIES: Record<string, string> = Object.assign(
    Object.create(null) as Record<string, string>,
    {
        "qail://core/orientation": ORIENTATION,
        "qail://core/cheatsheet": CHEATSHEET,
        "qail://core/schema-reference": SCHEMA_REFERENCE,
    },
);

export const KNOWLEDGE_RESOURCES: unknown[] = [
    {
        uri: "qail://core/orientation",
        name: "orientation",
        title: "QAIL Orientation",
        description:
            "What qail.rs is, the crate topology, a routing table from question shape to tool, and the schema-dialect warning. Load this before anything else.",
        mimeType: "text/markdown",
        annotations: { audience: ["assistant"], priority: 1.0 },
    },
    {
        uri: "qail://core/cheatsheet",
        name: "cheatsheet",
        title: "QAIL Cheatsheet",
        description:
            "One page: action keywords, clause order, and ~20 canonical query forms with the SQL they actually transpile to. Every line is copied from a verified example.",
        mimeType: "text/markdown",
        annotations: { audience: ["assistant"], priority: 0.9 },
    },
    {
        uri: "qail://core/schema-reference",
        name: "schema-reference",
        title: "QAIL Schema Reference",
        description:
            "The brace schema dialect, and which of the two brace parsers accepts what. Read before writing or editing any .qail schema.",
        mimeType: "text/markdown",
        annotations: { audience: ["assistant"], priority: 0.9 },
    },
];

/* -------------------------------------------------------------------------- */
/* Public surface consumed by index.ts                                        */
/* -------------------------------------------------------------------------- */

export function isKnowledgeTool(name: string): boolean {
    return TOOL_NAMES.has(name);
}

export function callKnowledgeTool(name: string, args: any): unknown {
    // Defensive: a malformed chunk or a corpus/index mismatch should surface as
    // an MCP tool error, never as a 500 from the Worker. The WASM tools cannot
    // throw; these must not either, or clients see two different failure modes
    // for the same endpoint.
    try {
        switch (name) {
            case "qail_search":
                return toolSearch(args ?? {});
            case "qail_doc":
                return toolDoc(args ?? {});
            case "qail_syntax":
                return toolSyntax(args ?? {});
            case "qail_examples":
                return toolExamples(args ?? {});
            case "qail_map":
                return toolMap(args ?? {});
            default:
                return toolError("Unknown knowledge tool: " + name);
        }
    } catch (err) {
        return toolError("Knowledge tool " + name + " failed: " + err);
    }
}

export function readKnowledgeResource(uri: string): string | null {
    return RESOURCE_BODIES[uri] ?? null;
}
