//! Branch SQL helpers for Data Virtualization
//!
//! Generates SQL for branch metadata management:
//! - Session variable injection (`app.branch_id`)
//! - DDL for internal `_qail_branches` + `_qail_branch_rows` tables
//! - Branch CRUD operations
//! - Merge logic (apply overlay → main tables)

/// Safely escape a SQL string literal value.
pub fn escape_literal(val: &str) -> String {
    let clean = val.replace('\0', "\u{FFFD}");
    if !clean.contains('\\') {
        return format!("'{}'", clean.replace('\'', "''"));
    }

    for idx in 0..=clean.len() {
        let tag = if idx == 0 {
            "qail_branch".to_string()
        } else {
            format!("qail_branch_{}", idx)
        };
        let delimiter = format!("${tag}$");
        if !clean.contains(&delimiter) {
            return format!("{delimiter}{clean}{delimiter}");
        }
    }

    format!("'{}'", clean.replace('\'', "''"))
}

/// SQL to set the branch context on a connection session.
pub fn branch_context_sql(branch_name: &str) -> String {
    format!(
        "BEGIN; SET LOCAL app.branch_id = {};",
        escape_literal(branch_name)
    )
}

/// SQL to reset (clear) the branch context.
pub fn branch_reset_sql() -> &'static str {
    "RESET app.branch_id;"
}

/// DDL to create the internal branch metadata tables.
/// Idempotent — uses IF NOT EXISTS.
pub fn create_branch_tables_sql() -> &'static str {
    r#"
CREATE TABLE IF NOT EXISTS _qail_branches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT UNIQUE NOT NULL,
    parent_branch_id UUID REFERENCES _qail_branches(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    merged_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'active'
);

CREATE TABLE IF NOT EXISTS _qail_branch_rows (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    branch_id UUID NOT NULL REFERENCES _qail_branches(id) ON DELETE CASCADE,
    table_name TEXT NOT NULL,
    row_pk TEXT NOT NULL,
    operation TEXT NOT NULL,
    row_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE _qail_branch_rows
    ADD COLUMN IF NOT EXISTS row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS idx_branch_rows_lookup
    ON _qail_branch_rows (branch_id, table_name, row_pk, row_seq DESC, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_branch_rows_branch
    ON _qail_branch_rows (branch_id, row_seq);
"#
}

/// SQL to create a new branch.
///
/// Branch names are validated to prevent SQL injection.
pub fn create_branch_sql(name: &str, parent: Option<&str>) -> String {
    let safe_name = escape_literal(name);
    match parent {
        Some(parent_name) => {
            let safe_parent = escape_literal(parent_name);
            format!(
                "INSERT INTO _qail_branches (name, parent_branch_id) \
                 SELECT {}, b.id \
                 FROM _qail_branches b \
                 WHERE b.name = {} AND b.status = 'active' \
                 RETURNING id, name, created_at;",
                safe_name, safe_parent
            )
        }
        None => format!(
            "INSERT INTO _qail_branches (name) VALUES ({}) RETURNING id, name, created_at;",
            safe_name
        ),
    }
}

/// SQL to list all branches.
pub fn list_branches_sql() -> &'static str {
    "SELECT id, name, parent_branch_id, created_at, merged_at, status \
     FROM _qail_branches ORDER BY created_at DESC;"
}

/// SQL to soft-delete a branch.
pub fn delete_branch_sql(name: &str) -> String {
    let safe_name = escape_literal(name);
    format!(
        "WITH target AS (\
           SELECT id FROM _qail_branches \
           WHERE name = {} AND status = 'active' \
           FOR UPDATE\
         ) \
         UPDATE _qail_branches b SET status = 'deleted' \
         FROM target \
         WHERE b.id = target.id \
         RETURNING b.id;",
        safe_name
    )
}

/// SQL to lock an active branch before merge.
///
/// Holding this row lock blocks concurrent overlay writes that use
/// `FOR KEY SHARE` until the merge commits or rolls back.
pub fn lock_active_branch_for_merge_sql(name: &str) -> String {
    let safe_name = escape_literal(name);
    format!(
        "SELECT id FROM _qail_branches \
         WHERE name = {} AND status = 'active' \
         FOR UPDATE;",
        safe_name
    )
}

/// SQL to verify that a branch exists and is active.
pub fn active_branch_exists_sql(name: &str) -> String {
    let safe_name = escape_literal(name);
    format!(
        "SELECT id FROM _qail_branches \
         WHERE name = {} AND status = 'active' \
         LIMIT 1;",
        safe_name
    )
}

/// SQL to read overlay rows for a branch on a specific table.
///
/// Returns the ordered operation stream so CoW reads can replay inserts,
/// patches, and tombstones chronologically.
pub fn read_overlay_sql(branch_name: &str, table_name: &str) -> String {
    let safe_branch = escape_literal(branch_name);
    let safe_table = escape_literal(table_name);
    format!(
        "SELECT row_pk, operation, row_data::text \
         FROM _qail_branch_rows \
         WHERE branch_id = (SELECT id FROM _qail_branches WHERE name = {} AND status = 'active') \
           AND table_name = {} \
         ORDER BY row_seq ASC NULLS FIRST, created_at ASC, id ASC;",
        safe_branch, safe_table
    )
}

/// SQL to insert a CoW write into the overlay.
///
/// # Arguments
///
/// * `branch_name` — Name of the branch to write to.
/// * `table_name` — Target table for the overlay row.
/// * `row_pk` — Primary key of the affected row.
/// * `operation` — Operation type (`insert`, `update`, `delete`).
pub fn write_overlay_sql(
    branch_name: &str,
    table_name: &str,
    row_pk: &str,
    operation: &str,
) -> String {
    let safe_branch = escape_literal(branch_name);
    let safe_table = escape_literal(table_name);
    let safe_pk = escape_literal(row_pk);
    let safe_op = escape_literal(operation);
    format!(
        "INSERT INTO _qail_branch_rows (branch_id, table_name, row_pk, operation, row_data) \
         SELECT b.id, {}, {}, {}, $1::jsonb \
         FROM _qail_branches b \
         WHERE b.name = {} AND b.status = 'active' \
         FOR KEY SHARE \
         RETURNING id;",
        safe_table, safe_pk, safe_op, safe_branch
    )
}

/// SQL to merge a branch — applies all overlay rows to the main tables.
///
/// This is a multi-step operation:
/// 1. For each 'insert' overlay: INSERT INTO main table
/// 2. For each 'update' overlay: UPDATE main table SET ... WHERE pk = ...
/// 3. For each 'delete' overlay: DELETE FROM main table WHERE pk = ...
/// 4. Mark branch as merged
///
/// Returns SQL to mark the branch as merged (the actual merge logic
/// is done in Rust by iterating overlay rows).
pub fn mark_merged_sql(name: &str) -> String {
    let safe_name = escape_literal(name);
    format!(
        "WITH target AS (\
           SELECT id FROM _qail_branches \
           WHERE name = {} AND status = 'active' \
           FOR UPDATE\
         ) \
         UPDATE _qail_branches b SET status = 'merged', merged_at = now() \
         FROM target \
         WHERE b.id = target.id \
         RETURNING b.id;",
        safe_name
    )
}

/// SQL to get overlay stats for a branch.
pub fn branch_stats_sql(name: &str) -> String {
    let safe_name = escape_literal(name);
    format!(
        "SELECT table_name, operation, COUNT(*) as count \
         FROM _qail_branch_rows \
         WHERE branch_id = (SELECT id FROM _qail_branches WHERE name = {} AND status = 'active') \
         GROUP BY table_name, operation \
         ORDER BY table_name, operation;",
        safe_name
    )
}

/// SQL to get all overlay rows for a branch, ordered for merge application.
///
/// Returns (table_name, row_pk, operation, row_data) tuples.
/// Order: by monotonic row_seq so operations are applied in the same global
/// order they were recorded. `created_at` and `id` are deterministic fallbacks
/// for pre-migration rows that do not have row_seq populated.
pub fn merge_overlay_rows_sql(name: &str) -> String {
    let safe_name = escape_literal(name);
    format!(
        "SELECT table_name, row_pk, operation, row_data::text \
         FROM _qail_branch_rows \
         WHERE branch_id = (SELECT id FROM _qail_branches WHERE name = {} AND status = 'active') \
         ORDER BY row_seq ASC NULLS FIRST, created_at ASC, id ASC;",
        safe_name
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_branch_context_sql() {
        let sql = branch_context_sql("feature-auth");
        assert_eq!(sql, "BEGIN; SET LOCAL app.branch_id = 'feature-auth';");
    }

    #[test]
    fn test_branch_context_sql_escapes_quotes() {
        let sql = branch_context_sql("it's a branch");
        assert_eq!(sql, "BEGIN; SET LOCAL app.branch_id = 'it''s a branch';");
    }

    #[test]
    fn test_branch_context_sql_preserves_backslashes() {
        let sql = branch_context_sql(r"feature\auth");
        assert_eq!(
            sql,
            r"BEGIN; SET LOCAL app.branch_id = $qail_branch$feature\auth$qail_branch$;"
        );
    }

    #[test]
    fn test_branch_context_sql_avoids_dollar_quote_collision() {
        let sql = branch_context_sql(r"feature $qail_branch$ \ auth");
        assert!(sql.contains(r"$qail_branch_1$feature $qail_branch$ \ auth$qail_branch_1$"));
    }

    #[test]
    fn test_create_branch_sql_no_parent() {
        let sql = create_branch_sql("dev", None);
        assert!(sql.contains("INSERT INTO _qail_branches"));
        assert!(sql.contains("'dev'"));
        assert!(!sql.contains("parent_branch_id"));
    }

    #[test]
    fn test_create_branch_sql_with_parent() {
        let sql = create_branch_sql("feature-1", Some("dev"));
        assert!(sql.contains("parent_branch_id"));
        assert!(sql.contains("'feature-1'"));
        assert!(sql.contains("'dev'"));
    }

    #[test]
    fn test_read_overlay_sql() {
        let sql = read_overlay_sql("feature-1", "users");
        assert!(!sql.contains("DISTINCT ON"));
        assert!(sql.contains("'feature-1'"));
        assert!(sql.contains("'users'"));
        assert!(sql.contains("status = 'active'"));
        assert!(sql.contains("ORDER BY row_seq ASC NULLS FIRST, created_at ASC, id ASC"));
    }

    #[test]
    fn test_lock_active_branch_for_merge_sql() {
        let sql = lock_active_branch_for_merge_sql("feature-1");
        assert!(sql.contains("SELECT id FROM _qail_branches"));
        assert!(sql.contains("'feature-1'"));
        assert!(sql.contains("status = 'active'"));
        assert!(sql.contains("FOR UPDATE"));
    }

    #[test]
    fn test_active_branch_exists_sql() {
        let sql = active_branch_exists_sql("feature-1");
        assert!(sql.contains("SELECT id FROM _qail_branches"));
        assert!(sql.contains("'feature-1'"));
        assert!(sql.contains("status = 'active'"));
        assert!(sql.contains("LIMIT 1"));
        assert!(!sql.contains("FOR UPDATE"));
    }

    #[test]
    fn test_write_overlay_sql() {
        let sql = write_overlay_sql("feat", "orders", "123", "insert");
        assert!(sql.contains("INSERT INTO _qail_branch_rows"));
        assert!(sql.contains("SELECT b.id"));
        assert!(sql.contains("FROM _qail_branches b"));
        assert!(sql.contains("'orders'"));
        assert!(sql.contains("'123'"));
        assert!(sql.contains("'insert'"));
        assert!(sql.contains("$1::jsonb"));
        assert!(sql.contains("status = 'active'"));
        assert!(sql.contains("FOR KEY SHARE"));
        assert!(sql.contains("RETURNING id"));
        assert!(!sql.contains("VALUES"));
    }

    #[test]
    fn test_delete_branch_sql_locks_active_branch() {
        let sql = delete_branch_sql("dev");
        assert!(sql.contains("WITH target AS"));
        assert!(sql.contains("status = 'active'"));
        assert!(sql.contains("FOR UPDATE"));
        assert!(sql.contains("status = 'deleted'"));
        assert!(sql.contains("RETURNING b.id"));
    }

    #[test]
    fn test_mark_merged_sql() {
        let sql = mark_merged_sql("dev");
        assert!(sql.contains("WITH target AS"));
        assert!(sql.contains("status = 'active'"));
        assert!(sql.contains("FOR UPDATE"));
        assert!(sql.contains("status = 'merged'"));
        assert!(sql.contains("merged_at = now()"));
        assert!(sql.contains("RETURNING b.id"));
    }

    #[test]
    fn test_merge_overlay_rows_sql_filters_active_branch() {
        let sql = merge_overlay_rows_sql("dev");
        assert!(sql.contains("status = 'active'"));
        assert!(!sql.contains("DISTINCT ON"));
        assert!(sql.contains("ORDER BY row_seq ASC NULLS FIRST, created_at ASC, id ASC"));
        assert!(!sql.contains("ORDER BY table_name, row_pk"));
    }

    #[test]
    fn test_branch_stats_sql_filters_active_branch() {
        let sql = branch_stats_sql("dev");
        assert!(sql.contains("status = 'active'"));
    }

    #[test]
    fn test_branch_rows_ddl_contains_monotonic_tie_breaker() {
        let sql = create_branch_tables_sql();
        assert!(sql.contains("row_seq BIGINT GENERATED BY DEFAULT AS IDENTITY"));
        assert!(sql.contains("ADD COLUMN IF NOT EXISTS row_seq"));
        assert!(sql.contains("row_seq DESC, created_at DESC"));
        assert!(sql.contains("branch_id, row_seq"));
    }
}
