use axum::{extract::State, response::IntoResponse};
use std::sync::Arc;

use crate::GatewayState;
use crate::auth::authenticate_request;
use crate::middleware::ApiError;

use super::types::{pg_type_to_ts, to_pascal_case};

/// GET /api/_schema/typescript — Auto-generated TypeScript interfaces
///
/// Produces TypeScript interface declarations for every table in the schema.
/// Returns `text/plain` (Content-Type: text/plain; charset=utf-8) so the
/// output can be piped directly to a `.d.ts` file.
///
/// **Security:** Requires authentication in production (same as `_schema`).
pub(crate) async fn typescript_types_handler(
    headers: axum::http::HeaderMap,
    State(state): State<Arc<GatewayState>>,
) -> Result<axum::response::Response, ApiError> {
    let auth = authenticate_request(state.as_ref(), &headers).await?;
    if !auth.is_authenticated() {
        return Err(ApiError::auth_error(
            "Authentication required for type generation",
        ));
    }
    if !auth.can_use_branching() {
        return Err(ApiError::forbidden(
            "Platform administrator role required for type generation",
        ));
    }

    let tables = state.schema.tables();
    let mut output = String::with_capacity(4096);

    output.push_str("// Auto-generated by Qail Gateway — do not edit\n");
    output.push_str("// Regenerate: curl -H 'Authorization: Bearer <token>' ");
    output.push_str("http://localhost:8080/api/_schema/typescript > types.d.ts\n\n");

    let mut table_names: Vec<&String> = tables.keys().collect();
    table_names.sort();

    for table_name in &table_names {
        let table = &tables[*table_name];
        let interface_name = to_pascal_case(table_name);

        output.push_str(&format!("export interface {} {{\n", interface_name));
        for col in &table.columns {
            let ts_type = pg_type_to_ts(&col.pg_type, col.nullable);

            let comment = if col.primary_key {
                " // PK".to_string()
            } else if let Some(ref fk) = col.foreign_key {
                format!(" // FK → {}.{}", fk.ref_table, fk.ref_column)
            } else {
                String::new()
            };

            output.push_str(&format!("  {}: {};{}\n", col.name, ts_type, comment));
        }
        output.push_str("}\n\n");
    }

    output.push_str("/** Map of table names to row types */\n");
    output.push_str("export interface DatabaseSchema {\n");
    for table_name in &table_names {
        let interface_name = to_pascal_case(table_name);
        output.push_str(&format!("  {}: {};\n", table_name, interface_name));
    }
    output.push_str("}\n");

    Ok((
        [(
            axum::http::header::CONTENT_TYPE,
            "text/plain; charset=utf-8",
        )],
        output,
    )
        .into_response())
}
