use axum::{extract::State, response::IntoResponse};
use std::collections::{HashMap, HashSet};
use std::sync::Arc;

use crate::GatewayState;
use crate::auth::authenticate_request;
use crate::middleware::ApiError;
use crate::schema::GatewayTable;

use super::types::{pg_type_to_ts, to_pascal_case};

fn ts_string_literal(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            ch if ch.is_control() => out.push_str(&format!("\\u{{{:x}}}", ch as u32)),
            ch => out.push(ch),
        }
    }
    out.push('"');
    out
}

fn is_ts_identifier_start(ch: char) -> bool {
    ch.is_ascii_alphabetic() || ch == '_' || ch == '$'
}

fn is_ts_identifier_part(ch: char) -> bool {
    is_ts_identifier_start(ch) || ch.is_ascii_digit()
}

fn is_ts_reserved_word(value: &str) -> bool {
    matches!(
        value,
        "break"
            | "case"
            | "catch"
            | "class"
            | "const"
            | "continue"
            | "debugger"
            | "default"
            | "delete"
            | "do"
            | "else"
            | "enum"
            | "export"
            | "extends"
            | "false"
            | "finally"
            | "for"
            | "function"
            | "if"
            | "import"
            | "in"
            | "instanceof"
            | "new"
            | "null"
            | "return"
            | "super"
            | "switch"
            | "this"
            | "throw"
            | "true"
            | "try"
            | "typeof"
            | "var"
            | "void"
            | "while"
            | "with"
            | "as"
            | "implements"
            | "interface"
            | "let"
            | "package"
            | "private"
            | "protected"
            | "public"
            | "static"
            | "yield"
            | "any"
            | "boolean"
            | "constructor"
            | "declare"
            | "get"
            | "module"
            | "require"
            | "number"
            | "set"
            | "string"
            | "symbol"
            | "type"
            | "from"
            | "of"
    )
}

fn sanitize_interface_base(table_name: &str) -> String {
    let pascal = to_pascal_case(table_name);
    let mut out = String::with_capacity(pascal.len().max(5));
    let mut capitalize_next = false;

    for ch in pascal.chars() {
        if is_ts_identifier_part(ch) {
            if out.is_empty() && !is_ts_identifier_start(ch) {
                out.push('T');
            }
            if capitalize_next {
                for upper in ch.to_uppercase() {
                    out.push(upper);
                }
                capitalize_next = false;
            } else {
                out.push(ch);
            }
        } else {
            capitalize_next = true;
        }
    }

    if out.is_empty() {
        out.push_str("Table");
    }
    if is_ts_reserved_word(&out) {
        out.push_str("Table");
    }
    out
}

fn table_interface_names(table_names: &[&String]) -> HashMap<String, String> {
    let mut used = HashSet::with_capacity(table_names.len());
    let mut names = HashMap::with_capacity(table_names.len());

    for table_name in table_names {
        let base = sanitize_interface_base(table_name);
        let mut candidate = base.clone();
        let mut suffix = 2usize;
        while used.contains(&candidate) {
            candidate = format!("{}{}", base, suffix);
            suffix += 1;
        }
        used.insert(candidate.clone());
        names.insert((*table_name).clone(), candidate);
    }

    names
}

fn generate_typescript_types(tables: &HashMap<String, GatewayTable>) -> String {
    let mut output = String::with_capacity(4096);

    output.push_str("// Auto-generated by Qail Gateway — do not edit\n");
    output.push_str("// Regenerate: curl -H 'Authorization: Bearer <token>' ");
    output.push_str("http://localhost:8080/api/_schema/typescript > types.d.ts\n\n");

    let mut table_names: Vec<&String> = tables.keys().collect();
    table_names.sort();
    let interface_names = table_interface_names(&table_names);

    for table_name in &table_names {
        let table = &tables[*table_name];
        let interface_name = &interface_names[*table_name];

        output.push_str(&format!("export interface {} {{\n", interface_name));
        for col in &table.columns {
            let ts_type = pg_type_to_ts(&col.pg_type, col.nullable);

            let comment = if col.primary_key {
                " // PK".to_string()
            } else if let Some(ref fk) = col.foreign_key {
                format!(" // FK → {}.{}", fk.ref_table, fk.ref_column)
            } else {
                String::new()
            };

            output.push_str(&format!(
                "  {}: {};{}\n",
                ts_string_literal(&col.name),
                ts_type,
                comment
            ));
        }
        output.push_str("}\n\n");
    }

    output.push_str("/** Map of table names to row types */\n");
    output.push_str("export interface DatabaseSchema {\n");
    for table_name in &table_names {
        let interface_name = &interface_names[*table_name];
        output.push_str(&format!(
            "  {}: {};\n",
            ts_string_literal(table_name),
            interface_name
        ));
    }
    output.push_str("}\n");

    output
}

/// GET /api/_schema/typescript — Auto-generated TypeScript interfaces
///
/// Produces TypeScript interface declarations for every table in the schema.
/// Returns `text/plain` (Content-Type: text/plain; charset=utf-8) so the
/// output can be piped directly to a `.d.ts` file.
///
/// **Security:** Requires authentication in production (same as `_schema`).
pub(crate) async fn typescript_types_handler(
    headers: axum::http::HeaderMap,
    State(state): State<Arc<GatewayState>>,
) -> Result<axum::response::Response, ApiError> {
    let auth = authenticate_request(state.as_ref(), &headers).await?;
    if !auth.is_authenticated() {
        return Err(ApiError::auth_error(
            "Authentication required for type generation",
        ));
    }
    if !auth.can_use_branching() {
        return Err(ApiError::forbidden(
            "Platform administrator role required for type generation",
        ));
    }

    let output = generate_typescript_types(state.schema.tables());

    Ok((
        [(
            axum::http::header::CONTENT_TYPE,
            "text/plain; charset=utf-8",
        )],
        output,
    )
        .into_response())
}

#[cfg(test)]
mod tests {
    use super::generate_typescript_types;
    use crate::schema::{GatewayColumn, GatewayTable};
    use std::collections::HashMap;

    fn column(name: &str, pg_type: &str) -> GatewayColumn {
        GatewayColumn {
            name: name.to_string(),
            col_type: pg_type.to_ascii_lowercase(),
            pg_type: pg_type.to_string(),
            nullable: false,
            primary_key: false,
            unique: false,
            has_default: false,
            foreign_key: None,
        }
    }

    fn table(name: &str, columns: Vec<GatewayColumn>) -> GatewayTable {
        GatewayTable {
            name: name.to_string(),
            columns,
            primary_key: None,
        }
    }

    fn render(tables: Vec<GatewayTable>) -> String {
        let tables = tables
            .into_iter()
            .map(|table| (table.name.clone(), table))
            .collect::<HashMap<_, _>>();
        generate_typescript_types(&tables)
    }

    #[test]
    fn leading_digit_table_name_gets_safe_interface_name() {
        let output = render(vec![table("123_accounts", vec![column("id", "INT4")])]);

        assert!(output.contains("export interface T123Accounts {"));
        assert!(output.contains("  \"id\": number;"));
        assert!(output.contains("  \"123_accounts\": T123Accounts;"));
        assert!(!output.contains("export interface 123"));
    }

    #[test]
    fn hyphenated_column_names_are_quoted_string_properties() {
        let output = render(vec![table(
            "users",
            vec![column("display-name", "TEXT"), column("email", "TEXT")],
        )]);

        assert!(output.contains("export interface Users {"));
        assert!(output.contains("  \"display-name\": string;"));
        assert!(output.contains("  \"email\": string;"));
        assert!(output.contains("  \"users\": Users;"));
        assert!(!output.contains("  display-name:"));
    }

    #[test]
    fn sanitized_interface_name_collisions_get_suffixes() {
        let output = render(vec![
            table("order-items", vec![column("id", "INT4")]),
            table("order_items", vec![column("id", "INT4")]),
        ]);

        assert!(output.contains("export interface OrderItems {"));
        assert!(output.contains("export interface OrderItems2 {"));
        assert!(output.contains("  \"order-items\": OrderItems;"));
        assert!(output.contains("  \"order_items\": OrderItems2;"));
    }
}
