//! Live PostgreSQL checks for the tenant stamp under INSERT OVERRIDING.
//!
//! PostgreSQL discards supplied values for identity columns under
//! `OVERRIDING USER VALUE`, for VALUES and SELECT sources alike, so an
//! injected tenant stamp on such a column is replaced by the sequence value.
//! `with_rls` refuses the clause; `OVERRIDING SYSTEM VALUE` keeps the stamp.
//!
//! Default local target:
//!   QAIL_TEST_DB_URL=postgres://qail_lab:qail_lab@127.0.0.1:55432/qail_engine_lab \
//!   cargo test -p qail-pg --test insert_overriding_live -- --ignored --nocapture

use qail_core::ast::{Qail, Value};
use qail_core::error::QailBuildError;
use qail_core::rls::RlsContext;
use qail_pg::{PgDriver, PgResult};

const TARGET: &str = "qail_ouv_probe";
const SOURCE: &str = "qail_ouv_probe_source";

fn database_url() -> String {
    std::env::var("QAIL_TEST_DB_URL").unwrap_or_else(|_| {
        "postgres://qail_lab:qail_lab@127.0.0.1:55432/qail_engine_lab".to_string()
    })
}

async fn returned_tenant(driver: &mut PgDriver, cmd: &Qail) -> PgResult<i64> {
    let rows = driver.fetch_all(cmd).await?;
    assert_eq!(rows.len(), 1, "one row inserted");
    Ok(rows[0].get_i64(0).expect("tenant_id"))
}

#[tokio::test]
#[ignore = "Requires a live PostgreSQL at QAIL_TEST_DB_URL"]
async fn overriding_user_value_discards_identity_tenant_stamp_and_with_rls_refuses_it()
-> PgResult<()> {
    qail_core::rls::init_scope_registries_from_tables(&[(TARGET, "tenant_id")], &[])
        .expect("boundary registration");
    let mut driver = PgDriver::connect_url(&database_url()).await?;
    driver
        .execute_simple(&format!(
            "CREATE TEMP TABLE {TARGET} (
                v text,
                tenant_id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 900)
            )"
        ))
        .await?;
    driver
        .execute_simple(&format!(
            "CREATE TEMP TABLE {SOURCE} (v text, tenant_id bigint);
             INSERT INTO {SOURCE} VALUES ('select-user-value', 42)"
        ))
        .await?;
    let tenant = RlsContext::tenant("42");

    // Server behavior without with_rls: the supplied 42 is discarded.
    let values_user = Qail::add(TARGET)
        .set_value("v", "values-user-value")
        .set_value("tenant_id", Value::Int(42))
        .overriding_user_value()
        .returning(["tenant_id"]);
    let stored = returned_tenant(&mut driver, &values_user).await?;
    println!("VALUES OVERRIDING USER VALUE, tenant_id supplied 42, stored {stored}");
    assert_ne!(stored, 42, "PostgreSQL replaced the supplied tenant value");

    let mut select_user = Qail::add(TARGET)
        .columns(["v", "tenant_id"])
        .overriding_user_value()
        .returning(["tenant_id"]);
    select_user.source_query = Some(Box::new(Qail::get(SOURCE).columns(["v", "tenant_id"])));
    let stored = returned_tenant(&mut driver, &select_user).await?;
    println!("INSERT ... SELECT OVERRIDING USER VALUE, tenant_id selected 42, stored {stored}");
    assert_ne!(stored, 42, "SELECT sources are discarded the same way");

    // with_rls refuses both shapes before anything reaches the server.
    for (shape, cmd) in [("VALUES", values_user), ("SELECT", select_user)] {
        let err = cmd
            .with_rls(&tenant)
            .expect_err("OVERRIDING USER VALUE must fail closed");
        println!("with_rls {shape} OVERRIDING USER VALUE: {err}");
        assert_eq!(
            err,
            QailBuildError::RlsInsertOverridingUserValueDenied {
                table: TARGET.to_string(),
                column: "tenant_id".to_string(),
            }
        );
    }

    // OVERRIDING SYSTEM VALUE keeps the stamp, replacing the forged value.
    let system = Qail::add(TARGET)
        .set_value("v", "system-value")
        .set_value("tenant_id", Value::Int(7))
        .overriding_system_value()
        .returning(["tenant_id"])
        .with_rls(&tenant)
        .expect("OVERRIDING SYSTEM VALUE is scoped");
    let stored = returned_tenant(&mut driver, &system).await?;
    println!("with_rls OVERRIDING SYSTEM VALUE, forged 7, stored {stored}");
    assert_eq!(stored, 42, "the tenant stamp landed");

    Ok(())
}
